<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=$title?> | МЕДИКА</title>
    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/animate.min.css" type="text/css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<?=$header?>

<section class="content section-field">
    <h3 class="section-title">О нас</h3>
    <div class="section-line"></div>
    <div class="container">
        <div class="row">
            <div class="col">
               <div class="section-content about-section">
                   <div class="text">
                       <p>Специализированный неврологический медицинский центр  <span style="display: block;">МЦ «МЕДИКА»/ ЖИТЬ БЕЗ БОЛИ</span></p>
                       <p>Мы рады, что вы выбрали Медицинский центр лечения боли « МЕДИКА» .
                       К сожалению, миллионы россиян вынуждены мириться с хронической
                       болью. Многие терпят ежедневные и ежечасные страдания, когда что-то
                       болит, долго, мучительно, иногда просто невыносимо.</p>
                       <p>Но от боли можно навсегда избавиться.</p>
                       <p>Наша клиника специализируется на лечении неврологических болезней. В
                       своей деятельности мы используем те методики лечения, которые позволяют
                       лечить хроническую боль. Задача нашего медицинского центра -помочь
                       пациентам в короткие сроки снять болевой синдром, для того, чтобы
                       вернуться к нормальной жизни. Лечение боли без операций с
                       использованием инновационных методик.</p>
                       <p><b>Мы лечим:</b></p>
                       <ul>
                           <li>остеохондроз, боли в спине</li>
                           <li>межпозвонковые грыжи, протрузии</li>
                           <li>суставные боли: артроз,артрит</li>
                           <li>головную боль, мигрень</li>
                           <li>боль в лице</li>
                           <li>нарушения сна</li>
                           <li>вегето-сосудистая дистония</li>
                           <li>пяточная шпора</li>
                           <li>восстановление нервов</li>
                           <li>боль в руках и шее</li>
                           <li>постоперационные боли</li>
                       </ul>
                       <p>Количество людей обращающихся к нам за помощью продолжает расти. </p>
                       <p>Мы со вниманием относимся к каждому пациенту.</p>
                       <p>У нас Вы можете записаться на прием
                       невролога,нейрохирурга,физиотерапевта.</p>
                       <p>Прием пациентов осуществляется по предварительной записи.</p>
                       <br />
                       <br />
                       <b>ЗАПИСАТЬСЯ НА ПРИЕМ</b> тел. +7 (8482) 49-08-39
                   </div>
               </div>
            </div>
        </div>
    </div>
</section>

<section class="galleria-license section-field">
    <h3 class="section-title">Лицензии</h3>
    <div class="section-line"></div>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="galleria-license__wrapper">
                    <?php
                        foreach ($licenses as $it){
                            ?>
                            <div class="galleria-license__item">
                                <a href="<?=$it['scan']?>" target="_blank" class="galleria-license__link" title="<?=$it['title']?>">
                                    <img src="<?=$it['preview']?>" alt="<?=$it['title']?>" class="galleria-license__image"/>
                                </a>
                            </div>
                            <?php
                        }
                    ?>
                </div>
            </div>
        </div>
    </div>
</section>

<?=$footer?>
</body>
</html>