<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=$title?> | МЕДИКА</title>
    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/animate.min.css" type="text/css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<?=$header?>

<section class="content section-field">
    <h3 class="section-title">О нас</h3>
    <div class="section-line"></div>
    <div class="container">
        <div class="row">
            <div class="col">
               <div class="section-content">
                   Специализированный неврологический медицинский центр
                   МЦ «МЕДИКА»/ ЖИТЬ БЕЗ БОЛИ
                   Мы рады, что вы выбрали Медицинский центр лечения боли « МЕДИКА» .
                   К сожалению, миллионы россиян вынуждены мириться с хронической
                   болью. Многие терпят ежедневные и ежечасные страдания, когда что-то
                   болит, долго, мучительно, иногда просто невыносимо.
                   Но от боли можно навсегда избавиться.
                   Наша клиника специализируется на лечении неврологических болезней. В
                   своей деятельности мы используем те методики лечения, которые позволяют
                   лечить хроническую боль. Задача нашего медицинского центра -помочь
                   пациентам в короткие сроки снять болевой синдром, для того, чтобы
                   вернуться к нормальной жизни. Лечение боли без операций с
                   использованием инновационных методик.
                   Мы лечим:
                   -остеохондроз, боли в спине
                   --межпозвонковые грыжи, протрузии
                   -суставные боли: артроз,артрит
                   -- головную боль, мигрень
                   -боль в лице
                   -нарушения сна
                   --вегето-сосудистая дистония
                   -пяточная шпора
                   -восстановление нервов
                   -боль в руках и шее
                   - постоперационные боли.
                   Количество людей обращающихся к нам за помощью продолжает расти. Мы
                   со вниманием относимся к каждому пациенту.
                   У нас Вы можете записаться на прием
                   невролога,нейрохирурга,физиотерапевта.
                   Прием пациентов осуществляется по предварительной записи.
                   ЗАПИСАТЬСЯ НА ПРИЕМ тел. +7 (8482) 49-08-39
               </div>
            </div>
        </div>
    </div>
</section>

<section class="galleria-license section-field">
    <h3 class="section-title">Лицензии</h3>
    <div class="section-line"></div>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="galleria-license__wrapper">
                    <?php
                        foreach ($licenses as $it){
                            ?>
                            <div class="galleria-license__item">
                                <a href="<?=$it['scan']?>" target="_blank" class="galleria-license__link" title="<?=$it['title']?>">
                                    <img src="<?=$it['preview']?>" alt="<?=$it['title']?>" class="galleria-license__image"/>
                                </a>
                            </div>
                            <?php
                        }
                    ?>
                </div>
            </div>
        </div>
    </div>
</section>

<?=$footer?>
</body>
</html>