<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />

    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>

    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
</head>
<body>
<?=$header?>

<section class="content section-field">
    <h3 class="section-title">О нас</h3>
    <div class="section-line"></div>
    <div class="container">
        <div class="row">
            <div class="col">
               <div class="section-content">Большой текст о нас</div>
            </div>
        </div>
    </div>
</section>

<section class="galleria-license section-field">
    <h3 class="section-title">Лицензии</h3>
    <div class="section-line"></div>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="galleria-license__wrapper">
                    <div class="galleria-license__item">
                        <a href="#" class="galleria-license__link">
                            <img src="/data/public/site/image/lic1.jpg" alt="img" class="galleria-license__image"/>
                        </a>
                    </div>
                    <div class="galleria-license__item">
                        <a href="#" class="galleria-license__link">
                            <img src="/data/public/site/image/lic2.jpg" alt="img" class="galleria-license__image"/>
                        </a>
                    </div>
                    <div class="galleria-license__item">
                        <a href="#" class="galleria-license__link">
                            <img src="/data/public/site/image/lic3.jpg" alt="img" class="galleria-license__image"/>
                        </a>
                    </div>
                    <div class="galleria-license__item">
                        <a href="#" class="galleria-license__link">
                            <img src="/data/public/site/image/lic4.jpg" alt="img" class="galleria-license__image"/>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?=$footer?>
</body>
</html>