<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=$title?> | МЕДИКА</title>
    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/animate.min.css" type="text/css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/data/public/site/favicon.ico" rel="shortcut icon"/>
    <meta name="description" content="Наша клиника специализируется на лечении неврологических болезней. В своей деятельности мы используем те методики лечения, которые позволяют лечить хроническую боль."/>
    <meta name="keywords" content="МЕДИКА medica лечение неврология тольятти центр суставы спина услуги">
</head>
<body>
<?=$header?>
<section class="content section-field">
    <h1 class="content__title">Что мы лечим</h1>
    <div class="content__line"></div>
        <div class="container">
            <div class="row">
                <div class="col">
                    <div id="skeleton">
                        <?php
                            foreach ($pains as $pain){
                                echo "<a href='/pain/$pain[id]/' style='top: $pain[top]px;left: $pain[left]px' id='disease:$pain[id]'>$pain[title]</a>";
                            }
                        ?>
                    </div>
                </div>
            </div>
        </div>
</section>


<?=$footer?>
</body>
</html>