<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
</head>
<body>
<?=$header?>
<section class="content section-field">
    <h1 class="content__title">Что мы лечим</h1>
    <div class="content__line"></div>
        <div class="container">
            <div class="row">
                <div class="col">
                    Боляки моляки ЦЕЕЕЕЕЕЕЕЕЛЫЙ СПИСОК
                </div>
            </div>
        </div>
</section>


<?=$footer?>
</body>
</html>