<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />

</head>
<body>
    <header class="info grey-field">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="info__left-panel align-middle">
                        <div class="info__work-static">
                            Режим работы:
                        </div>
                        <div class="info__item">
                            <span class="info__days">Пн-Пт:</span>
                            <span class="info__time-work">8:00 - 18:00</span>
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="info__right-panel">
                        <div class="info__address">
                            40 лет Победы 126.(вход с торца)
                        </div>
                        <div class="info__phone">
                            <span>тел:</span> 49-08-39, 55-55-85
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="head">
        <div class="container">
            <div class="row">
                <div class="col-2">
                    <div class="head__logo">
                        <a href="#">
                            <img src="/data/public/site/image/logo.jpg" alt="logo"/>
                        </a>
                    </div>
                </div>
                <div class="col-10">
                    <ul class="nav justify-content-end">
                        <li class="nav-link head__item head__item--active">
                            <a href="#">Что мы лечим</a>
                        </li>
                        <li class="nav-link head__item"><a href="#">Методы лечения</a></li>
                        <li class="nav-link head__item"><a href="#">Врачи</a></li>
                        <li class="nav-link head__item"><a href="#">О нас</a></li>
                        <li class="nav-link head__item"><a href="#">Цены</a></li>
                        <li class="nav-link head__item"><a href="#">Контакты</a></li>
                    </ul>
                    <!-- <div class="dropdown head__menu-smart">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Кнопка выпадающего списка
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </div>



    <div id="carouselSlideMedika" class="carousel slide">
        <ol class="carousel-indicators">
            <li data-target="#carouselSlideMedika" data-slide-to="0" class="active"></li>
            <li data-target="#carouselSlideMedika" data-slide-to="1"></li>
            <li data-target="#carouselSlideMedika" data-slide-to="2"></li>
        </ol>

        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="/data/public/site/image/slide-1.jpg" alt="Первый слайд">

                <div class="slider__cont-text">
                    <h3 class="slider__title">
                        Акция!
                    </h3>
                    <div class="slider__content-text">
                        При покупки пакета курсы на лечение грыжи, предоставляем последующую скидку в размере 100 рублей на каждый сеанс, после завершение курса.
                    </div>
                    <button class="btn btn--red">
                        Купить
                    </button>
                </div>
            </div>

            <div class="carousel-item">
                <img class="d-block w-100" src="/data/public/site/image/slide-1.jpg" alt="Первый слайд">
            </div>

            <div class="carousel-item">
                <img class="d-block w-100" src="/data/public/site/image/slide-1.jpg" alt="Первый слайд">
            </div>

            <a class="carousel-control-prev" href="#carouselSlideMedika" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselSlideMedika" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <!-- Перенести в лицензии -->
    <div class="galleria-license">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h3 class="section-title">Лицензии</h3>
                    <div class="section-line"></div>
                    <div class="galleria-license__wrapper">
                        <div class="galleria-license__item">
                            <a href="#" class="galleria-license__link">
                                <img src="/data/public/site/image/lic1.jpg" alt="img" class="galleria-license__image"/>
                            </a>
                        </div>
                        <div class="galleria-license__item">
                            <a href="#" class="galleria-license__link">
                                <img src="/data/public/site/image/lic2.jpg" alt="img" class="galleria-license__image"/>
                            </a>
                        </div>
                        <div class="galleria-license__item">
                            <a href="#" class="galleria-license__link">
                                <img src="/data/public/site/image/lic3.jpg" alt="img" class="galleria-license__image"/>
                            </a>
                        </div>
                        <div class="galleria-license__item">
                            <a href="#" class="galleria-license__link">
                                <img src="/data/public/site/image/lic4.jpg" alt="img" class="galleria-license__image"/>
                            </a>
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
    <div class="reviews">
        <div class="section-title">Отзывы о нас!</div>
        <div class="section-line"></div>
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="reviews__answer">
                        <div class="reviews__ava-views">
                            <img src="/data/public/site/image/man1.png" class="reviews__ava" alt="Аватарка"/>
                        </div>
                        <div class="reviews__text">
                            аывпва вап вап вап вап вап вап вап вап вап ва вап ва пва пвап ва вап вап вап вап вап вап вап вап
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="reviews__answer reviews__answer--right-photo">
                        <div class="reviews__text">
                            аывпва вап вап вап вап вап вап вап вап вап ва вап ва пва пвап ва вап вап вап вап вап вап вап вап

                        </div>
                        <div class="reviews__ava-views">
                            <img src="/data/public/site/image/man2.png" class="reviews__ava" alt="Аватарка"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="reviews__answer">
                        <div class="reviews__ava-views">
                            <img src="/data/public/site/image/man3.png" class="reviews__ava" alt="Аватарка"/>
                        </div>
                        <div class="reviews__text">
                            аывпва вап вап вап вап вап вап вап вап вап ва вап ва пва пвап ва вап вап вап вап вап вап вап вап
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="arrow-down">

    </div>
    <footer class="footer-site grey-field">
        <div class="container">
            <div class="footer">
                <div class="section-title">Давайте оставаться на связи!</div>
                <div class="section-line"></div>
                <div class="footer__text">Готовы начать свой следующий проект с нами? Замечательно! Позвоните нам или отправьте нам письмо, и мы свяжемся с вами как можно скорее!</div>
                <div class="footer__boxes">
                    <div class="footer__box">
                        <img src="/data/public/site/image/phone.svg" alt="Телефон">
                        <ul>
                            <li><a href="#">49-08-39</a></li>
                            <li><a href="#">55-55-85</a></li>
                        </ul>
                    </div>
                    <div class="footer__box">
                        <img src="/data/public/site/image/email.svg" alt="email">
                        <ul>
                            <li><a href="#">mcmedica@mail.ru</a></li>
                        </ul>
                    </div>
                </div>
                <div class="footer__line"></div>
                <div class="footer__text">А так же мы будем рады видеть вас в наших группах в соц. сетях.</div>
                <div class="footer__boxes">
                    <div class="footer__box">
                        <a href="#">
                            <img src="/data/public/site/image/vk.svg" alt="vk">
                            <div>Вконтакте</div>
                        </a>
                    </div>
                    <div class="footer__box">
                        <a href="#">
                            <img src="/data/public/site/image/ok.svg" alt="ok">
                            <div>Одноклассники</div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom">
            <div class="bottom__links">
                <a href="#">Техническая поддержка</a>
                <a href="#">MirCom 2019</a>
            </div>
        </div>
    </footer>
    <script src="/data/public/site/scripts.js"></script>
</body>
</html>