<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $title ?> | МЕДИКА</title>
    <link href="/data/public/site/favicon.ico" rel="shortcut icon"/>
    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet"/>
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet"/>
    <link href="/data/public/site/animate.min.css" type="text/css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Наша клиника специализируется на лечении неврологических болезней. В своей деятельности мы используем те методики лечения, которые позволяют лечить хроническую боль."/>
    <meta name="keywords" content="МЕДИКА medica лечение неврология тольятти центр суставы спина услуги">
    <link href="https://fonts.googleapis.com/css?family=PT+Serif" rel="stylesheet">
</head>
<body>
<?= $header ?>
<?php
if (count($sliders) > 0) {
    ?>

    <div id="carouselSlideMedika" class="carousel slide">
        <ol class="carousel-indicators">
            <?php
            foreach ($sliders as $index => $it) {
                echo "<li data-target='#carouselSlideMedika' data-slide-to='${index}' class='" . ($index === 0 ? 'active' : '') . "'></li>";
            }
            ?>
        </ol>

        <div class="carousel-inner">
            <?php
            foreach ($sliders as $index => $it) {
                $itemClass = $index === 0 ? 'carousel-item active' : 'carousel-item';

                ?>
                <div class="<?= $itemClass ?>">
                    <div class="d-block w-100 slider__image" style="background-image: url(<?=$it['image'] ?>)" title="<?=$it['title'] ?>"></div>
                    <?php
                        if(!empty($it['title']) || !empty($it['title']) || !empty($it['title'])){
                            ?>
                                <div class="slider__cont-text">
                                    <h1 class="slider__title">
                                        <?= $it['title'] ?>
                                    </h1>
                                    <?php
                                    if (!empty($it['text'])) {
                                        echo "<div class='slider__content-text'>${it['text']}</div>";
                                    }
                                    ?>
                                    <?php
                                    if (!empty($it['href'])) {
                                        echo "<a class='btn btn--red' href='${it['href']}'>Перейти</a>";
                                    }
                                    ?>
                                </div>
                            <?php
                        }
                    ?>
                </div>
                <?php
            }
            ?>
            <a class="carousel-control-prev" href="#carouselSlideMedika" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselSlideMedika" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>


        </div>

    </div>


    <?php
}
?>

<section class="content" style="padding-top: 60px">
    <h1 class="content__title">Что мы лечим</h1>
    <div class="content__line"></div>
    <div class="skeleton">
        <div class="skeleton__fon"></div>
        <div class="skeleton__image">
            <?php
            foreach ($pains as $pain){
                echo "<a href='/pain/$pain[id]/' style='top: $pain[top]%;left: $pain[left]%' id='disease:$pain[id]'>$pain[title]</a>";
            }
            ?>
        </div>
    </div>
</section>



<section class="reviews section-field">
    <div class="section-title">Методы лечения</div>
    <div class="section-line"></div>
    <div class="container">
        <div class="container treatment-list">
            <?php
            foreach ($methods as $i => $method) {
                ?>
                <a class="treatment-list__item" href="/treatment/<?=$method['id']?>/">
                    <div
                            class="treatment-list__preview"
                            style="background-image: url('<?=empty($method["preview_image"]) ? '/src/adminPanel/no_image.png' : $method["preview_image"]?>')"
                    ></div>
                    <h3 class="treatment-list__title"><?=$method['title']?></h3>
                </a>
                <?php
            }
            ?>
        </div>
    </div>
</section>
<div class="arrow-down">

</div>
<?= $footer ?>


</body>
</html>