<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=$title?> | МЕДИКА</title>
    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>
    <script src="/data/public/site/jquery-migrate-3.0.0.min.js"></script>
    <script src="/data/public/site/waypoints.min.js"></script>
    <script src="/data/public/site/animate-css.js"></script>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/animate.min.css" type="text/css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<?=$header?>

<section class="section-field not-found-page">
    <div class="container">
        <div class="row">
            <div class="col">
               <h2><span>404</span> - Страница не найдена.</h2>
            </div>
        </div>
    </div>
</section>

<?=$footer?>
</body>
</html>