<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=$pain['title']?> | МЕДИКА</title>
    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/animate.min.css" type="text/css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://maps.api.2gis.ru/2.0/loader.js?pkg=full"></script>
    <link href="/data/public/site/favicon.ico" rel="shortcut icon"/>
    <meta name="description" content="Наша клиника специализируется на лечении неврологических болезней. В своей деятельности мы используем те методики лечения, которые позволяют лечить хроническую боль."/>
    <meta name="keywords" content="МЕДИКА medica лечение неврология тольятти центр суставы спина">
</head>
<body>
<?=$header?>
<section class="content section-field section-pain">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="content__center">
                    <h1 class="section-title"><?=$pain['title']?></h1>
                    <div class="section-line"></div>
                    <div class="content__wrapper">
                        <div class="text">
                            <?=$pain['text']?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<?=$footer?>
</body>
</html>