<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=$post['title']?> | МЕДИКА</title>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
</head>
<body>
<?=$header?>
<section class="content section-field">
    <div class="container">
        <div class="row">
            <div class="col">
                <h3 class="section-title">Статья</h3>
                <div class="section-line"></div>
                <?=print_r($post)?>
            </div>
        </div>
    </div>
</section>
<?=$footer?>
</body>
</html>