<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=$post['title']?> | МЕДИКА</title>
    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>
    <script src="/data/public/site/jquery-migrate-3.0.0.min.js"></script>
    <script src="/data/public/site/waypoints.min.js"></script>
    <script src="/data/public/site/animate-css.js"></script>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/animate.min.css" type="text/css" rel="stylesheet" />
</head>
<body>
<?=$header?>
<section class="content section-field">
    <div class="container">
        <div class="row">
            <div class="col">
                <h3 class="section-title"><?=$post['title']?></h3>
                <div class="section-line"></div>
                <!-- <?=print_r($post)?> -->
                <div class="article-new">
                    <div class="article-new__text">
                        <?=$post['text']?>
                    </div>

                    <div class="article-new__date-wrapper">
                        <span class="article-new__date">
                            <?=date('d.m.Y',strtotime($post['date']))?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?=$footer?>


    <script src="/data/public/site/animationElement.js"></script>
</body>
</html>