<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=$title?> | МЕДИКА</title>
    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>
    <script src="/data/public/site/jquery-migrate-3.0.0.min.js"></script>
    <script src="/data/public/site/waypoints.min.js"></script>
    <script src="/data/public/site/animate-css.js"></script>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/animate.min.css" type="text/css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<?=$header?>
<section class="content section-field articles-page">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h3 class="section-title">Статьи</h3>
                <div class="section-line"></div>
                <div class="articles-list">
                    <div class="row">
                        <?php foreach ($posts as $item) {?>
                            <div class="articles-list__title">
                                <a href="#post:<?=$item['id']?>"><?=$item['title']?></a>
                            </div>
                        <?php } ?>
                    </div>
                    <?php foreach ($posts as $item) {?>
                        <div class="row" id="post:<?=$item['id']?>
">
                            <div class="col-3">
                                <div class="articles-list__wrapper-image">
                                    <a href="/posts/<?=$item['id']?>/">
                                        <img src="<?=$item['preview_image']?>" class="articles-list__image" alt="Картинка новости">
                                    </a>
                                </div>
                            </div>
                            <div class="col-9">
                                <div class="articles-list__title">
                                    <?=$item['title']?>
                                </div>
                                <div class="articles-list__text">
                                    <?=$item['preview_text']?>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</section>
<?=$footer?>
<script src="/data/public/site/animationElement.js"></script>
</body>
</html>