<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=$title?> | МЕДИКА</title>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <?=$header?>
    <section class="content section-field">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h3 class="section-title">Цены</h3>
                    <div class="section-line"></div>
                    <table class="table table-striped table-hover prices-table">
                        <thead>
                        <tr>
                            <th scope="col">Название</th>
                            <th scope="col">Цена</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($prices as $item) {?>
                            <tr>
                                <td><?=$item['name']?></td>
                                <td><?=$item['price']?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>    
    </section>
    <?=$footer?>
</body>
</html>