<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?=$title?> | МЕДИКА</title>
        <script src="/data/public/site/jquery.min.js"></script>
        <script src="/data/public/site/popper.min.js"></script>
        <script src="/data/public/site/bootstrap.min.js"></script>
        <script src="/data/public/site/jquery-migrate-3.0.0.min.js"></script>
        <script src="/data/public/site/waypoints.min.js"></script>
        <script src="/data/public/site/animate-css.js"></script>
        <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
        <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
        <link href="/data/public/site/animate.min.css" type="text/css" rel="stylesheet" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
    <?=$header?>

    <section class="content section-field">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="content__center">
                        <h1 class="section-title">Сотрудники</h1>
                        <div class="section-line"></div>
                        <div class="content__wrapper">
                            <div class="staff">
                                    <?php
                                        foreach ($staff as $it) {
                                    ?>
                                            <div class="staff__row">
                                                <div class="row">
                                                    <div class="col-4">
                                                        <div class="staff__photo-wrapper">
                                                            <img src="<?=$it['photo']?>" class="staff__photo" alt="photo" />
                                                        </div>
                                                    </div>
                                                    <div class="col-8">
                                                        <div class="staff__profile">
                                                            <h3 class="staff__title">
                                                                <?=$it['fullname']?>
                                                            </h3>
                                                            <div class="staff__text">
                                                                <?=$it['about']?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                    <?php
                                        }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <div>
        </section>
    <?=$footer?>
    </body>
</html>