<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=$title?> | МЕДИКА</title>
    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/animate.min.css" type="text/css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/data/public/site/favicon.ico" rel="shortcut icon"/>
    <meta name="description" content="Наша клиника специализируется на лечении неврологических болезней. В своей деятельности мы используем те методики лечения, которые позволяют лечить хроническую боль."/>
    <meta name="keywords" content="МЕДИКА medica лечение неврология тольятти центр суставы спина">
    <link href="https://fonts.googleapis.com/css?family=PT+Serif" rel="stylesheet">
</head>
<body>
<?=$header?>
<section class="content section-field treatment-form">
    <h1 class="content__title">Методы лечения</h1>
    <div class="content__line"></div>
        <div class="container treatment-list">
            <?php
                foreach ($methods as $i => $method) {
                    ?>
                        <a class="treatment-list__item" href="/treatment/<?=$method['id']?>/">
                            <div
                                    class="treatment-list__preview"
                                    style="background-image: url('<?=empty($method["preview_image"]) ? '/src/adminPanel/no_image.png' : $method["preview_image"]?>')"
                            ></div>
                            <h3 class="treatment-list__title"><?=$method['title']?></h3>
                        </a>
                    <?php
                }
            ?>
        </div>
</section>


<?=$footer?>
</body>
</html>