<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=$title?> | МЕДИКА</title>
    <script src="/data/public/site/jquery.min.js"></script>
    <script src="/data/public/site/popper.min.js"></script>
    <script src="/data/public/site/bootstrap.min.js"></script>
    <link href="/data/public/site/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/styles.css" type="text/css" rel="stylesheet" />
    <link href="/data/public/site/animate.min.css" type="text/css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<?=$header?>
<section class="content section-field">
    <h1 class="content__title">Методы лечения</h1>
    <div class="content__line"></div>
        <div class="container">
            <?php
                foreach ($methods as $i => $method) {
                    echo '<div>'.($i + 1)." <a href='/treatment/$method[id]/'>$method[title]</a></div>";
                }
            ?>
        </div>
</section>


<?=$footer?>
</body>
</html>