<style>
    .modal-dialog{
        max-width: 98vw;
    }
</style>

<h4>
    Боли
    <button type="button" class="btn btn-primary btn-create">
        <i class="fa fa-plus" aria-hidden="true"></i> Создать боль
    </button>
</h4>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название</th>
            <th scope="col">Опции</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($pains as $pain) {?>
            <tr>
                <td><?=$pain['id']?></td>
                <td><?=$pain['title']?></td>
                <td>
                    <div class="btn-group btn-group-sm" role="group">
                        <button type="button" class="btn btn-info btn-edit" title="Редактировать" data-id="<?=$pain['id']?>">
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                        </button>
                        <button type="button" class="btn btn-danger btn-delete" title="Удалить" data-id="<?=$pain['id']?>">
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<script>
    var $body = $('body');

    //удаление боли
    $body.on('click', '.btn-delete', function () {
    	if(confirm('Вы уверены?')){
    		var id = $(this).data('id');
		    $.ajax({
			    url: '/admin/delete/pain/'+id+'/',
			    type: 'DELETE',
			    success: function(result) {
			    	alert(result.status ? 'Запись удалена' : 'Ошибка');
			    	if(result.status) location.reload();
			    },
                error: function () {
	                alert('Ошибка');
                }
		    });
        }
    });

    //создать боль
    $body.on('click', '.btn-create', function () {
	    $.ajax({
		    url: '/admin/form/pain/',
		    type: 'GET',
		    success: function(result) {
			    if(!result.status) return alert('Ошибка');
			    var $form = $(result.data);
			    $('textarea.editor', $form).each(function () {
				    ClassicEditor
					    .create(this, {
						    ckfinder: {
							    uploadUrl: '/admin/upload/pain/'
						    }
					    })
					    .catch( error => {
						    console.error('ClassicEditor err: ', error);
					    } );
			    });
			    var $dialog = $('#dialog');
			    $('.modal-body', $dialog).html($form);
			    $('.modal-title', $dialog).html('Создание боли');
			    $dialog.modal();
		    },
		    error: function () {
			    alert('Ошибка');
		    }
	    });
    });

    //редактирование боли
    $body.on('click', '.btn-edit', function () {
	    var id = $(this).data('id');
	    $.ajax({
		    url: '/admin/form/pain/'+id+'/',
		    type: 'GET',
		    success: function(result) {
			    if(!result.status) return alert('Ошибка');
                var $form = $(result.data);
			    $form.find('textarea.editor').each(function () {
				    ClassicEditor
					    .create(this, {
						    ckfinder: {
							    uploadUrl: '/admin/upload/pain/'
						    }
					    })
					    .catch( error => {
						    console.error('ClassicEditor err: ', error);
					    } );
			    });
			    $form.attr('method', 'put');
			    $form.attr('action', '/admin/save/pain/'+id+'/');
			    var $dialog = $('#dialog');
                $('.modal-body', $dialog).html($form);
                $('.modal-title', $dialog).html('Редактирование боли');
			    $dialog.modal();
		    },
		    error: function () {
			    alert('Ошибка');
		    }
	    });
    });
</script>