<form class="ajax" method="post" action="/admin/save/emails/" autocomplete="off">
    <div class="form-group">
        <label for="email">E-mail</label>
        <input value="<?=(isset($data['email']) ? $data['email'] : '')?>" name="email" type="email" class="form-control" id="email" placeholder="Введите E-mail" required>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>