<form class="ajax" method="post" action="/admin/save/licenses/" autocomplete="off">
    <div class="form-group">
        <label for="licenseScan">
            <img
                width="100"
                alt="preview"
                src="<?=(!isset($data['scan']) || empty($data['scan'])) ? '/src/adminPanel/no_image.png' : $data['scan']?>"
            />
        </label>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="licenseScan" accept="image/*" data-folder="licenses" />
            <input required type="hidden" name="scan" value="<?=isset($data['scan']) ? $data['scan'] : $data['scan']?>"/>
            <label class="custom-file-label" for="licenseScan">Скан лицензии</label>
        </div>
    </div>
    <div class="form-group">
        <label for="licenseTitle">Название</label>
        <input value="<?=isset($data['title']) ? $data['title'] : ''?>" name="title" type="text" class="form-control" id="licenseTitle" placeholder="Введите название" required>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>