<form class="ajax" method="post" action="/admin/save/methods/" autocomplete="off">
    <div class="form-group">
        <label for="methodName">Название метода</label>
        <input value="<?=isset($data['title']) ? $data['title'] : ''?>" name="title" type="text" class="form-control" id="methodName" placeholder="Введите заголовок" required>
    </div>
    <div class="form-group">
        <label for="methodText">Текст</label>
        <textarea class="form-control editor" id="methodText" name="text" ><?=isset($data['text']) ? $data['text'] : ''?></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>