<form class="ajax" method="post" action="/admin/save/methods/" autocomplete="off">
    <div class="form-group">
        <label for="methodsPreviewImage">
            <img
                    width="100"
                    alt="preview"
                    src="<?=!isset($data['preview_image']) && empty($data['preview_image']) ? '/src/adminPanel/no_image.png' : $data['preview_image']?>"
            />
        </label>
        <a href="javascript:void(0)" onClick="$('[type=hidden]', $(this).parent()).val('')">Удалить файл</a>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="methodsPreviewImage" accept="image/*" data-folder="methods" />
            <input type="hidden" name="preview_image" value="<?=$data['preview_image']?>"/>
            <label class="custom-file-label" for="methodsPreviewImage">Превью</label>
        </div>
    </div>
    <div class="form-group">
        <label for="methodName">Название метода</label>
        <input value="<?=isset($data['title']) ? $data['title'] : ''?>" name="title" type="text" class="form-control" id="methodName" placeholder="Введите заголовок" required>
    </div>
    <div class="form-group">
        <label for="methodText">Текст</label>
        <textarea class="form-control editor" id="methodText" name="text" ><?=isset($data['text']) ? $data['text'] : ''?></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>