<form class="ajax" method="post" action="/admin/save/reviews/" autocomplete="off">
    <div class="form-group">
        <label for="serviceName">ФИО клиента</label>
        <input value="<?=(isset($data['user_name']) ? $data['user_name'] : '')?>" name="user_name" type="text" class="form-control" id="serviceName" placeholder="Введите ФИО" required>
    </div>

    <div class="form-group">
        <label for="previewAvatar">
            <img
                width="100"
                alt="avatar"
                src="<?=!isset($data['avatar']) && empty($data['avatar']) ? '/src/adminPanel/no_image.png' : $data['avatar']?>"
            />
        </label>
        <a href="javascript:void(0)" onClick="$('[type=hidden]', $(this).parent()).val('')">Удалить файл</a>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="previewAvatar" accept="image/*" data-folder="previews" />
            <input type="hidden" name="avatar" value="<?=$data['avatar']?>"/>
            <label class="custom-file-label" for="previewAvatar">Аватарка пользователя</label>
        </div>
    </div>

    <div class="form-group">
        <label for="previewText">Текст отзыва</label>
        <textarea class="form-control editor" id="previewText" name="text" ><?=isset($data['text']) ? $data['text'] : ''?></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>