<form class="ajax" method="post" action="/admin/save/slides/" autocomplete="off">
    <div class="form-group">
        <label for="sliderImage">
            <img
                    width="100"
                    alt="image"
                    src="<?=empty($data['image']) ? '/src/adminPanel/no_image.png' : $data['image']?>"
            />
        </label>
        <a href="javascript:void(0)" onClick="$('[type=hidden]', $(this).parent()).val('')">Удалить файл</a>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="sliderImage" accept="image/*" data-folder="slider" />
            <input type="hidden" name="image" value="<?=isset($data['image']) ? $data['image'] : ''?>"/>
            <label class="custom-file-label" for="sliderImage">Превью</label>
        </div>
    </div>
    <div class="form-group">
        <label for="slideName">Название</label>
        <input value="<?=isset($data['title']) ? $data['title'] : ''?>" name="title" type="text" class="form-control" id="slideName" placeholder="Введите заголовок" >
    </div>
    <div class="form-group">
        <label for="slideHref">Ссылка</label>
        <input value="<?=isset($data['href']) ? $data['href'] : ''?>" name="href" type="text" class="form-control" id="slideHref" placeholder="Введите ссылку" >
    </div>
    <div class="form-group">
        <label for="slideText">Описание</label>
        <input value="<?=isset($data['text']) ? $data['text'] : ''?>" name="text" type="text" class="form-control" id="slideText" placeholder="Введите описание" >
    </div>
    <div class="form-group">
        <label for="slideStatus">Статус слайда</label>
        <select class="form-control" id="slideStatus" name="status">
            <option <?=(isset($data['status']) && $data['status'] === '0' ? 'selected' : '')?> value="0">Не опубликован</option>
            <option <?=(isset($data['status']) && $data['status'] === '1' ? 'selected' : '')?> value="1">Опубликован</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>