<form class="ajax" method="post" action="/admin/save/slides/" autocomplete="off">
    <div class="form-group">
        <label for="sliderImage">
            <img
                width="100"
                alt="image"
                src="<?=empty($data['image']) ? '/src/adminPanel/no_image.png' : $data['image']?>"
            />
        </label>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="sliderImage" accept="image/*" data-folder="slider" />
            <input type="hidden" name="image" value="<?=$data['image']?>"/>
            <label class="custom-file-label" for="sliderImage">Превью</label>
        </div>
    </div>
    <div class="form-group">
        <label for="slideName">Название</label>
        <input value="<?=$data['title']?>" name="title" type="text" class="form-control" id="slideName" placeholder="Введите заголовок" required>
    </div>
    <div class="form-group">
        <label for="slideStatus">Статус слайда</label>
        <select class="form-control" id="slideStatus" name="status">
            <option <?=($data['status'] === '0' ? 'selected' : '')?> value="0">Не опубликован</option>
            <option <?=($data['status'] === '1' ? 'selected' : '')?> value="1">Опубликован</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>