<div class="bottomForm">
    <h2 class="bottomForm__title">Остались вопросы? Или хотите поделится проблемой? <br /> - Оставьте свой номер и мы свяжемся с вами</h2>
    <div class="bottomForm__badge">Услуга бесплатна!</div>
    <form class="form-inline bottomForm__form ajax">
        <input type="hidden" name="type" value="question"/>
        <div class="row">
            <div class="col">
                <input required type="text"  name="fullname" class="form-control" placeholder="Имя">
            </div>
            <div class="col">
                <input required type="text" name="phone" class="form-control" placeholder="Телефон">
            </div>
            <div class="col">
                <button type="submit" class="btn btn-primary btn-danger">Отправить</button>
            </div>
            <div class="col">
                <div class="result_form"></div>
            </div>
        </div>
    </form>
</div>
<footer class="footer-site grey-field section-field">
    <div class="container">
        <div class="footer">
            <div class="section-title">Давайте оставаться на связи!</div>
            <div class="section-line"></div>
            <div class="footer__text">Позвоните нам или отправьте нам письмо, и мы свяжемся с вами как можно скорее!</div>
            <div class="footer__boxes">
                <div class="footer__box footer__box--left">
                    <img src="/data/public/site/image/phone.svg" alt="Телефон">
                    <ul>
                        <li><a href="tel:490839">49-08-39</a></li>
                        <li><a href="tel:555585">55-55-85</a></li>
                    </ul>
                </div>
                <div class="footer__box footer__box--right">
                    <img src="/data/public/site/image/email.svg" alt="email">
                    <ul>
                        <li><a href="mailto:mcmedica@mail.ru">mcmedica@mail.ru</a></li>
                    </ul>
                </div>
            </div>
            <div class="section-line "></div>
            <div class="footer__text">А так же мы будем рады видеть вас в наших группах в соц. сетях.</div>
            <div class="footer__boxes">
                <div class="footer__box">
                    <a href="https://vk.com/id367722327" target="_blank">
                        <img src="/data/public/site/image/vk.svg" alt="vk">
                        <div>Вконтакте</div>
                    </a>
                </div>
                <div class="footer__box">
                    <a href="https://ok.ru/profile/574853239267/pphotos/835302655971" target="_blank">
                        <img src="/data/public/site/image/ok.svg" alt="ok">
                        <div>Одноклассники</div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom">
        <div class="bottom__links">
            <a href="https://vk.com/mironov_oleg">MirCom 2019</a>
        </div>
    </div>
</footer>
<script src="/data/public/site/scripts.js" type="application/javascript"></script>