<footer class="footer-site grey-field section-field"">
    <div class="container">
        <div class="footer">
            <div class="section-title">Давайте оставаться на связи!</div>
            <div class="section-line"></div>
            <div class="footer__text">Готовы начать свой следующий проект с нами? Замечательно! Позвоните нам или отправьте нам письмо, и мы свяжемся с вами как можно скорее!</div>
            <div class="footer__boxes">
                <div class="footer__box footer__box--left">
                    <img src="/data/public/site/image/phone.svg" alt="Телефон">
                    <ul>
                        <li><a href="#">49-08-39</a></li>
                        <li><a href="#">55-55-85</a></li>
                    </ul>
                </div>
                <div class="footer__box footer__box--right">
                    <img src="/data/public/site/image/email.svg" alt="email">
                    <ul>
                        <li><a href="#">mcmedica@mail.ru</a></li>
                    </ul>
                </div>
            </div>
            <div class="section-line "></div>
            <div class="footer__text">А так же мы будем рады видеть вас в наших группах в соц. сетях.</div>
            <div class="footer__boxes">
                <div class="footer__box">
                    <a href="#">
                        <img src="/data/public/site/image/vk.svg" alt="vk">
                        <div>Вконтакте</div>
                    </a>
                </div>
                <div class="footer__box">
                    <a href="#">
                        <img src="/data/public/site/image/ok.svg" alt="ok">
                        <div>Одноклассники</div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom">
        <div class="bottom__links">
            <a href="#">Техническая поддержка</a>
            <a href="#">MirCom 2019</a>
        </div>
    </div>
</footer>