<form class="ajax" method="post" action="/send_request/" autocomplete="off">
    <div class="form-group">
        <label for="form:phone">Контактный телефон</label>
        <input name="phone" type="text" class="form-control" id="form:phone" placeholder="Введите телефон" required>
    </div>
    <div class="form-group">
        <label for="form:name">ФИО</label>
        <input name="fullname" type="text" class="form-control" id="form:name" placeholder="Введите ФИО" required>
    </div>
    <button type="submit" class="btn btn-primary">Отправить</button>
</form>