<button type="button" class="btn  btn-danger btn-primary button-show-form" data-toggle="modal" data-target="#exampleModalCenter">
  Записаться на прием
</button>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Запись на прием</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form class="ajax" method="post" action="/send_request/" autocomplete="off">
            <div class="form-group">
                <label for="form:phone">Контактный телефон</label>
                <input name="phone" type="text" class="form-control" id="form:phone" placeholder="Введите телефон" required>
            </div>
            <div class="form-group">
                <label for="form:name">ФИО</label>
                <input name="fullname" type="text" class="form-control" id="form:name" placeholder="Введите ФИО" required>
            </div>
            <button type="submit" class="btn btn-danger send-button">Отправить</button>
            <div class="result_form"></div>
        </form>
      </div>
    </div>
  </div>
</div>