<header class="info grey-field">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="info__left-panel align-middle">
                    <div class="info__work-static">
                        Режим работы:
                    </div>
                    <div class="info__item">
                        <span class="info__days">Пн-Пт:</span>
                        <span class="info__time-work">8:00 - 18:00</span>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="info__right-panel">
                    <div class="info__address">
                        40 лет Победы 126.<span class="info__text-tip">(вход с торца)</span>
                    </div>
                    <div class="info__phone">
                        <span class="info__text-phone">тел:</span> <span class="info__num-phone">49-08-39,</span> <span class="info__num-phone">55-55-85</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<?=$form?>
<div class="head">
    <div class="container">
        <div class="row">
            <div class="col-2">
                <div class="head__logo">
                    <a href="/">
                        <img src="/data/public/site/image/logo.jpg" alt="logo"/>
                    </a>
                </div>
            </div>
            <div class="col-10">


            <?=$menu?>


            </div>
        </div>
    </div>
</div>