<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
	(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
		m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
	(window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

	ym(52331500, "init", {
		id:52331500,
		clickmap:true,
		trackLinks:true,
		accurateTrackBounce:true,
		webvisor:true
	});
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/52331500" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<header class="info grey-field">
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <div class="info__left-panel align-middle">
                    <div class="info__work-static">
                        Режим работы:
                    </div>
                    <div class="info__item">
                        <span class="info__days">Пн-Пт:</span>
                        <span class="info__time-work">8:00 - 18:00</span>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <a href="/">
                    <img style="top: 5px;position: relative;" alt="logo" src="/data/public/site/image/oldLogo.png" />
                </a>
            </div>
            <div class="col-sm">
                <div class="info__right-panel">
                    <div class="info__address">
                        40 лет Победы 126.<span class="info__text-tip">(вход с торца)</span>
                    </div>
                    <div class="info__phone">
                        <span class="info__text-phone">тел:</span>
                        <a href="tel:490839" class="info__num-phone">49-08-39,</a>
                        <a href="tel:555585" class="info__num-phone">55-55-85</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<?=$form?>
<div class="head">
    <div class="container">
        <div class="row">
            <div class="col-2">
                <div class="head__logo">
                    <a href="/">
                        <img height="90" src="/data/public/site/image/newLogo.png" alt="logo"/>
                    </a>
                </div>
            </div>
            <div class="col-10">


            <?=$menu?>


            </div>
        </div>
    </div>
</div>